// Package core implements strsweep's local-only scan and rewrite engine.
package core

import (
	"bytes"
	"crypto/sha256"
	"fmt"
	"go/ast"
	"go/parser"
	"go/scanner"
	"go/token"
	"io/fs"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strconv"
	"strings"
)

const GeneratedName = "strsweep_const.go"
const Marker = "// Code generated by strsweep. DO NOT EDIT."

type Row struct {
	Path                       string
	Detected, Excluded, Target int
	Status                     string
}
type literal struct {
	start, end int
	value      string
}
type source struct {
	info     fs.FileInfo
	path     string
	data     []byte
	mode     fs.FileMode
	row      *Row
	literals []literal
}
type pkg struct {
	dirInfo      fs.FileInfo
	dir, name    string
	files        []*source
	names        map[string]bool
	declarations map[string]bool
	values       map[string]string
	counts       map[string]int
	old          *source
	conflict     bool
	mixed        bool
}
type Candidate struct {
	Package, Name, Value string
	Count                int
}
type Result struct {
	rootInfo   fs.FileInfo
	Root       string
	Rows       []*Row
	Candidates []Candidate
	packages   []*pkg
}

// Scan never writes files. It stops parsing at the first non-excluded syntax error.
func Scan(root string, progress func(int, int, string)) (*Result, error) {
	abs, err := filepath.Abs(root)
	if err != nil {
		return nil, err
	}
	pinned, err := pinRoot(abs, nil)
	if err != nil {
		return nil, err
	}
	defer pinned.root.Close()
	r := &Result{Root: abs, rootInfo: pinned.info}
	var paths []string
	err = fs.WalkDir(pinned.root.FS(), ".", func(path string, d fs.DirEntry, e error) error {
		if e != nil {
			return e
		}
		if d.Type()&os.ModeSymlink != 0 {
			return nil
		}
		if d.IsDir() {
			if path != "." && (d.Name() == "vendor" || d.Name() == "testdata" || strings.HasPrefix(d.Name(), ".")) {
				return filepath.SkipDir
			}
			return nil
		}
		if d.Type().IsRegular() && strings.HasSuffix(path, ".go") {
			paths = append(paths, filepath.FromSlash(path))
		}
		return nil
	})
	if err != nil {
		return r, err
	}
	sort.Strings(paths)
	groups := map[string]*pkg{}
	for _, path := range paths {
		rel := path
		r.Rows = append(r.Rows, &Row{Path: filepath.ToSlash(rel), Status: "未処理"})
	}
	for i, path := range paths {
		row := r.Rows[i]
		if progress != nil {
			progress(i+1, len(paths), row.Path)
		}
		data, info, e := readRegular(pinned.root, path)
		if e != nil {
			row.Status = "エラー（読込失敗）"
			return r, fmt.Errorf("%s: %w", row.Path, e)
		}
		relativePath := path
		path = filepath.Join(abs, path)
		dir := filepath.Dir(path)
		p := groups[dir]
		if p == nil {
			p = &pkg{dir: dir, names: map[string]bool{}, declarations: map[string]bool{}, values: map[string]string{}, counts: map[string]int{}}
			dirInfo, e := pinned.root.Lstat(filepath.Dir(relativePath))
			if e != nil {
				return r, e
			}
			p.dirInfo = dirInfo
			groups[dir] = p
			r.packages = append(r.packages, p)
		}
		own := filepath.Base(path) == GeneratedName && hasMarker(data)
		skip := ""
		if strings.HasSuffix(path, "_test.go") {
			skip = "テスト"
		} else if generated(data) {
			skip = "生成コード"
		}
		if own {
			skip = "生成済み定数"
		}
		fset := token.NewFileSet()
		tree, e := parser.ParseFile(fset, path, data, parser.ParseComments|parser.AllErrors)
		if e != nil && (skip == "" || own) {
			row.Status = "エラー（構文解析失敗）"
			return r, fmt.Errorf("%s: %w", row.Path, e)
		}
		src := &source{path: path, data: data, mode: info.Mode(), row: row, info: info}
		if tree != nil {
			ast.Inspect(tree, func(n ast.Node) bool {
				if selector, ok := n.(*ast.SelectorExpr); ok && !own {
					if id, ok := selector.X.(*ast.Ident); ok {
						p.declarations[id.Name] = true
					}
				}
				if id, ok := n.(*ast.Ident); ok {
					p.names[id.Name] = true
					if !own && id.Obj != nil && id.Obj.Pos() == id.Pos() {
						p.declarations[id.Name] = true
					}
				}
				return true
			})
			// Test files never participate in directory package-name selection.
			if !strings.HasSuffix(path, "_test.go") {
				if p.name == "" {
					p.name = tree.Name.Name
				} else if p.name != tree.Name.Name {
					p.mixed = true
				}
			}
			excluded := map[*ast.BasicLit]bool{}
			ast.Inspect(tree, func(n ast.Node) bool {
				switch v := n.(type) {
				case *ast.ImportSpec:
					excluded[v.Path] = true
					if !own && v.Name != nil {
						p.declarations[v.Name.Name] = true
					}
				case *ast.Field:
					if v.Tag != nil {
						excluded[v.Tag] = true
					}
				case *ast.GenDecl:
					if v.Tok == token.CONST {
						ast.Inspect(v, func(n ast.Node) bool {
							if lit, ok := n.(*ast.BasicLit); ok {
								excluded[lit] = true
							}
							return true
						})
					}
				}
				return true
			})
			ast.Inspect(tree, func(n ast.Node) bool {
				lit, ok := n.(*ast.BasicLit)
				if !ok || lit.Kind != token.STRING {
					return true
				}
				row.Detected++
				value, e := strconv.Unquote(lit.Value)
				if e != nil {
					return true
				}
				if skip != "" || excluded[lit] || value == "" {
					row.Excluded++
					return true
				}
				start := fset.Position(lit.Pos()).Offset
				end := start + len(lit.Value)
				if data[start] == '`' {
					if j := bytes.IndexByte(data[start+1:], '`'); j >= 0 {
						end = start + j + 2
					}
				}
				src.literals = append(src.literals, literal{start, end, value})
				row.Target++
				return true
			})
		}
		if filepath.Base(path) == GeneratedName {
			if own {
				p.old = src
				if e = readExisting(tree, p); e != nil {
					row.Status = "エラー（生成済み定数）"
					return r, fmt.Errorf("%s: %w", row.Path, e)
				}
			} else {
				p.conflict = true
			}
		}
		if skip != "" {
			row.Status = "スキップ（" + skip + "）"
		} else {
			p.files = append(p.files, src)
			if row.Target > 0 {
				row.Status = "置換予定"
			} else {
				row.Status = "対象なし"
			}
		}
	}
	for _, p := range r.packages {
		if p.old == nil {
			if _, e := pinned.root.Lstat(filepath.Join(packageRelative(abs, p.dir), GeneratedName)); e == nil {
				p.conflict = true
			} else if !os.IsNotExist(e) {
				return r, e
			}
		}
		reason := ""
		if p.conflict {
			reason = "生成先の衝突"
		}
		if p.mixed {
			reason = "複数パッケージ"
		}
		if reason != "" {
			for _, s := range p.files {
				s.row.Status = "スキップ（" + reason + "）"
				s.row.Excluded += s.row.Target
				s.row.Target = 0
				s.literals = nil
			}
			continue
		}
		for _, s := range p.files {
			for _, lit := range s.literals {
				p.counts[lit.value]++
			}
		}
		vals := make([]string, 0, len(p.counts))
		for v := range p.counts {
			vals = append(vals, v)
		}
		sort.Strings(vals)
		for _, v := range vals {
			if name, ok := p.values[v]; ok && p.declarations[name] {
				for _, s := range p.files {
					if s.row.Target > 0 {
						s.row.Status = "エラー（生成済み定数の識別子衝突）"
					}
				}
				return r, fmt.Errorf("existing generated constant %s is shadowed by a declaration; rename the conflicting declaration before retrying", name)
			}
			if _, ok := p.values[v]; !ok {
				base := BaseName(v)
				name := base
				for n := 2; p.names[name]; n++ {
					name = base + strconv.Itoa(n)
				}
				p.names[name] = true
				p.values[v] = name
			}
			rel, _ := filepath.Rel(abs, p.dir)
			r.Candidates = append(r.Candidates, Candidate{filepath.ToSlash(rel), p.values[v], v, p.counts[v]})
		}
	}
	sort.Slice(r.Candidates, func(i, j int) bool {
		a, b := r.Candidates[i], r.Candidates[j]
		if a.Package != b.Package {
			return a.Package < b.Package
		}
		return a.Name < b.Name
	})
	return r, nil
}
func hasMarker(data []byte) bool {
	line, _, _ := bytes.Cut(data, []byte("\n"))
	return string(bytes.TrimSuffix(line, []byte("\r"))) == Marker
}

var generatedLine = regexp.MustCompile(`(?m)^// Code generated .* DO NOT EDIT\.\r?$`)

func generated(data []byte) bool {
	var scan scanner.Scanner
	fset := token.NewFileSet()
	scan.Init(fset.AddFile("", -1, len(data)), data, func(token.Position, string) {}, scanner.ScanComments)
	for {
		_, tok, lit := scan.Scan()
		if tok == token.EOF {
			return false
		}
		if tok == token.COMMENT && strings.HasPrefix(lit, "//") && generatedLine.MatchString(lit) {
			return true
		}
	}
}

var words = regexp.MustCompile(`[A-Za-z0-9]+`)

// BaseName is deterministic; collision suffixes are assigned after sorting values.
func BaseName(value string) string {
	parts := words.FindAllString(value, 4)
	if len(parts) == 0 {
		return fmt.Sprintf("strLit%x", sha256.Sum256([]byte(value)))[:12]
	}
	s := "str"
	for _, part := range parts {
		part = strings.ToLower(part)
		s += strings.ToUpper(part[:1]) + part[1:]
	}
	return s
}
func readExisting(tree *ast.File, p *pkg) error {
	if tree == nil {
		return fmt.Errorf("invalid generated file")
	}
	used := map[string]bool{}
	for _, decl := range tree.Decls {
		g, ok := decl.(*ast.GenDecl)
		if !ok || g.Tok != token.CONST {
			return fmt.Errorf("generated file contains non-constant declarations")
		}
		for _, spec := range g.Specs {
			v := spec.(*ast.ValueSpec)
			if len(v.Names) != 1 || len(v.Values) != 1 || v.Type != nil {
				return fmt.Errorf("unsupported generated constant")
			}
			lit, ok := v.Values[0].(*ast.BasicLit)
			if !ok || lit.Kind != token.STRING {
				return fmt.Errorf("unsupported generated constant")
			}
			value, e := strconv.Unquote(lit.Value)
			if e != nil {
				return e
			}
			name := v.Names[0].Name
			if !strings.HasPrefix(name, "str") || used[name] {
				return fmt.Errorf("invalid generated constant name: %s", name)
			}
			used[name] = true
			if _, ok := p.values[value]; ok {
				return fmt.Errorf("duplicate generated value")
			}
			p.values[value] = name
		}
	}
	return nil
}

func packageRelative(root, dir string) string { rel, _ := filepath.Rel(root, dir); return rel }
